### PR TITLE
Added restart unless stopped docker-publish.yml

### PR DESCRIPTION
**Pull request by zynfox**
Restart the docker container unless stopped.

### CODE REVIEW

**Comment by shawaj** [comment]
Don't know if this is a valid option? 

https://github.com/docker/build-push-action?tab=readme-ov-file#inputs

**Comment by zynfox** [comment]
> Don't know if this is a valid option?
> 
> https://github.com/docker/build-push-action?tab=readme-ov-file#inputs

My apologies, you're correct.

I was thinking restart: unless-stopped inside docker compose file, which I see is already there.
So does mean docker run -d --restart unless-stopped isn't required anymore when running this?

**Comment by shawaj** [comment]
> > Don't know if this is a valid option?
> > https://github.com/docker/build-push-action?tab=readme-ov-file#inputs
> 
> My apologies, you're correct.
> 
> I was thinking restart: unless-stopped inside docker compose file, which I see is already there. So does mean docker run -d --restart unless-stopped isn't required anymore when running this?

It depends how you run it. 

You would need to run using `docker compose up`

I'm making a guide but haven't finished yet

**Comment by zynfox** [comment]
Closing as the proper format is restart: unless-stopped inside docker compose file, which already exists thanks to @shawaj.

**Pull request closed without merging**
